<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>assert.rejects(asyncFn[, error][, message]) | Node.js API 文档</title>
  <link rel="icon" sizes="32x32" type="image/png" href="http://static.nodejs.cn/_static/img/favicon.png"><link rel="stylesheet" href="/api/api.css">
  <script>
    document.write('<link href="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port?'':'//static.nodejs.cn')&#32;+&#32;'/_static/css/api.css?1576756292595" rel="stylesheet">')
  </script>
</head>
<body class="alt apidoc" id="page_api_item">
  <div id="api-section-assert">
    <div id="content" class="clearfix">
  
      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>assert.rejects(asyncFn[, error][, message])</h1>
          <div id="gtoc">
            <ul>
              <li>v12.14.0</li>
              <li>
                <a href="../assert.html#assert_assert_rejects_asyncfn_error_message" name="toc">返回上层文档</a>
              </li>
              <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/assert/assert_rejects_asyncfn_error_message.md" rel="nofollow" target="_blank">提交修改</a>
              </li>
              <li>
                <a href="http://nodejs.cn/search" name="toc">搜索</a>
              </li>
            </ul>
          </div>
          <hr>
        </header>

        <div id="biz_item"></div>
  
        <div id="apicontent">
          <div id="content_left"><div class="api_metadata">
<span>&#x65B0;&#x589E;&#x4E8E;: v10.0.0</span>
</div><ul>
<li><code>asyncFn</code> <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a> | <a href="http://nodejs.cn/s/ri1kj8" target="_blank" rel="nofollow" class="type">&lt;Promise&gt;</a></li>
<li><code>error</code> <a href="http://nodejs.cn/s/G38byW" target="_blank" rel="nofollow" class="type">&lt;RegExp&gt;</a> | <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a> | <a href="http://nodejs.cn/s/jzn6Ao" target="_blank" rel="nofollow" class="type">&lt;Object&gt;</a> | <a href="http://nodejs.cn/s/qZ873x" target="_blank" rel="nofollow" class="type">&lt;Error&gt;</a></li>
<li><code>message</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a></li>
</ul><p>&#x7B49;&#x5F85; <code>asyncFn</code> Promise&#xFF0C;&#x6216;&#x8005;&#xFF0C;&#x5982;&#x679C; <code>asyncFn</code> &#x662F;&#x4E00;&#x4E2A;&#x51FD;&#x6570;&#xFF0C;&#x5219;&#x7ACB;&#x5373;&#x8C03;&#x7528;&#x8BE5;&#x51FD;&#x6570;&#x5E76;&#x7B49;&#x5F85;&#x8FD4;&#x56DE;&#x7684; Promise &#x5B8C;&#x6210;&#x3002;
&#x7136;&#x540E;&#x5B83;&#x5C06;&#x68C0;&#x67E5; Promise &#x662F;&#x5426;&#x88AB;&#x62D2;&#x7EDD;&#x3002;</p><p>&#x5982;&#x679C; <code>asyncFn</code> &#x662F;&#x4E00;&#x4E2A;&#x51FD;&#x6570;&#x5E76;&#x4E14;&#x5B83;&#x540C;&#x6B65;&#x629B;&#x51FA;&#x4E00;&#x4E2A;&#x9519;&#x8BEF;&#xFF0C;&#x5219; <code>assert.rejects()</code> &#x5C06;&#x8FD4;&#x56DE;&#x4E00;&#x4E2A;&#x5E26;&#x6709;&#x8BE5;&#x9519;&#x8BEF;&#x7684;&#x88AB;&#x62D2;&#x7EDD;&#x7684; <code>Promise</code>&#x3002;
&#x5982;&#x679C;&#x51FD;&#x6570;&#x672A;&#x8FD4;&#x56DE; Promise&#xFF0C;&#x5219; <code>assert.rejects()</code> &#x5C06;&#x8FD4;&#x56DE;&#x4E00;&#x4E2A;&#x88AB;&#x62D2;&#x7EDD;&#x7684; <code>Promise</code>&#xFF0C;&#x5176;&#x4E2D;&#x5305;&#x542B; <a href="http://nodejs.cn/s/zKCD5R" rel="nofollow"><code>ERR_INVALID_RETURN_VALUE</code></a> &#x9519;&#x8BEF;&#x3002;
&#x5728;&#x8FD9;&#x4E24;&#x79CD;&#x60C5;&#x51B5;&#x4E0B;&#x90FD;&#x4F1A;&#x8DF3;&#x8FC7;&#x9519;&#x8BEF;&#x5904;&#x7406;&#x51FD;&#x6570;&#x3002;</p><p>&#x9664;&#x4E86;&#x7B49;&#x5F85;&#x7684;&#x5F02;&#x6B65;&#x6027;&#x8D28;&#x4E4B;&#x5916;&#xFF0C;&#x5B8C;&#x6210;&#x884C;&#x4E3A;&#x4E0E; <a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a> &#x5B8C;&#x5168;&#x76F8;&#x540C;&#x3002;</p><p>&#x5982;&#x679C;&#x6307;&#x5B9A;&#xFF0C;&#x5219; <code>error</code> &#x53EF;&#x4EE5;&#x662F; <a href="http://nodejs.cn/s/5wDLcp" rel="nofollow"><code>Class</code></a>&#x3001;<a href="http://nodejs.cn/s/tbQJCP" rel="nofollow"><code>RegExp</code></a>&#x3001;&#x9A8C;&#x8BC1;&#x51FD;&#x6570;&#x3001;&#x5C06;&#x6D4B;&#x8BD5;&#x6BCF;&#x4E2A;&#x5C5E;&#x6027;&#x7684;&#x5BF9;&#x8C61;&#x3001;&#x6216;&#x8005;&#x5C06;&#x6D4B;&#x8BD5;&#x6BCF;&#x4E2A;&#x5C5E;&#x6027;&#x7684;&#x9519;&#x8BEF;&#x5B9E;&#x4F8B;&#xFF08;&#x5305;&#x62EC;&#x4E0D;&#x53EF;&#x679A;&#x4E3E;&#x7684; <code>message</code> &#x548C; <code>name</code> &#x5C5E;&#x6027;&#xFF09;&#x3002;</p><p>&#x5982;&#x679C;&#x6307;&#x5B9A; <code>message</code>&#xFF0C;&#x5219;&#x5F53; <code>asyncFn</code> &#x65E0;&#x6CD5;&#x62D2;&#x7EDD;&#x65F6; <code>message</code> &#x5C06;&#x662F; <code>AssertionError</code> &#x63D0;&#x4F9B;&#x7684;&#x6D88;&#x606F;&#x3002;</p><pre><code class="language-js">(async () =&gt; {
  await assert.rejects(
    async () =&gt; {
      throw new TypeError(&apos;&#x9519;&#x8BEF;&#x503C;&apos;);
    },
    {
      name: &apos;TypeError&apos;,
      message: &apos;&#x9519;&#x8BEF;&#x503C;&apos;
    }
  );
})();
</code></pre><pre><code class="language-js">assert.rejects(
  Promise.reject(new Error(&apos;&#x9519;&#x8BEF;&#x503C;&apos;)),
  Error
).then(() =&gt; {
  // ...
});
</code></pre><p>&#x6CE8;&#x610F;&#xFF0C; <code>error</code> &#x4E0D;&#x80FD;&#x662F;&#x5B57;&#x7B26;&#x4E32;&#x3002;
&#x5982;&#x679C;&#x63D0;&#x4F9B;&#x4E86;&#x4E00;&#x4E2A;&#x5B57;&#x7B26;&#x4E32;&#x4F5C;&#x4E3A;&#x7B2C;&#x4E8C;&#x4E2A;&#x53C2;&#x6570;&#xFF0C;&#x5219;&#x5047;&#x5B9A; <code>error</code> &#x88AB;&#x5FFD;&#x7565;&#xFF0C;&#x800C;&#x5B57;&#x7B26;&#x4E32;&#x5C06;&#x7528;&#x4E8E; <code>message</code>&#x3002;
&#x8FD9;&#x53EF;&#x80FD;&#x5BFC;&#x81F4;&#x5BB9;&#x6613;&#x9519;&#x8FC7;&#x7684;&#x9519;&#x8BEF;&#x3002;
&#x5982;&#x679C;&#x8003;&#x8651;&#x4F7F;&#x7528;&#x5B57;&#x7B26;&#x4E32;&#x4F5C;&#x4E3A;&#x7B2C;&#x4E8C;&#x4E2A;&#x53C2;&#x6570;&#xFF0C;&#x8BF7;&#x4ED4;&#x7EC6;&#x9605;&#x8BFB; <a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a> &#x4E2D;&#x7684;&#x793A;&#x4F8B;&#x3002;</p></div>
          <div id="content_right"><div class="api_metadata">
<span>Added in: v10.0.0</span>
</div><ul>
<li><code>asyncFn</code> <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a> | <a href="http://nodejs.cn/s/ri1kj8" target="_blank" rel="nofollow" class="type">&lt;Promise&gt;</a></li>
<li><code>error</code> <a href="http://nodejs.cn/s/G38byW" target="_blank" rel="nofollow" class="type">&lt;RegExp&gt;</a> | <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a> | <a href="http://nodejs.cn/s/jzn6Ao" target="_blank" rel="nofollow" class="type">&lt;Object&gt;</a> | <a href="http://nodejs.cn/s/qZ873x" target="_blank" rel="nofollow" class="type">&lt;Error&gt;</a></li>
<li><code>message</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a></li>
</ul><p>Awaits the <code>asyncFn</code> promise or, if <code>asyncFn</code> is a function, immediately
calls the function and awaits the returned promise to complete. It will then
check that the promise is rejected.</p><p>If <code>asyncFn</code> is a function and it throws an error synchronously,
<code>assert.rejects()</code> will return a rejected <code>Promise</code> with that error. If the
function does not return a promise, <code>assert.rejects()</code> will return a rejected
<code>Promise</code> with an <a href="http://nodejs.cn/s/zKCD5R" rel="nofollow"><code>ERR_INVALID_RETURN_VALUE</code></a> error. In both cases the error
handler is skipped.</p><p>Besides the async nature to await the completion behaves identically to
<a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a>.</p><p>If specified, <code>error</code> can be a <a href="http://nodejs.cn/s/5wDLcp" rel="nofollow"><code>Class</code></a>, <a href="http://nodejs.cn/s/tbQJCP" rel="nofollow"><code>RegExp</code></a>, a validation function,
an object where each property will be tested for, or an instance of error where
each property will be tested for including the non-enumerable <code>message</code> and
<code>name</code> properties.</p><p>If specified, <code>message</code> will be the message provided by the <code>AssertionError</code> if
the <code>asyncFn</code> fails to reject.</p><pre><code class="language-js">(async () =&gt; {
  await assert.rejects(
    async () =&gt; {
      throw new TypeError(&apos;Wrong value&apos;);
    },
    {
      name: &apos;TypeError&apos;,
      message: &apos;Wrong value&apos;
    }
  );
})();
</code></pre><pre><code class="language-js">assert.rejects(
  Promise.reject(new Error(&apos;Wrong value&apos;)),
  Error
).then(() =&gt; {
  // ...
});
</code></pre><p><code>error</code> cannot be a string. If a string is provided as the second
argument, then <code>error</code> is assumed to be omitted and the string will be used for
<code>message</code> instead. This can lead to easy-to-miss mistakes. Please read the
example in <a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a> carefully if using a string as the second
argument gets considered.</p></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.write('<script src="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port&#32;?&#32;''&#32;:&#32;'//static.nodejs.cn')&#32;+&#32;'/_static/js/api.js?1576756292595"><\/script>');
  </script>
</body>
</html>